package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* loaded from: classes.dex */
final class zzdb {

    /* renamed from: a, reason: collision with root package name */
    public static final BillingResult f2064a;
    public static final BillingResult b;

    /* renamed from: c, reason: collision with root package name */
    public static final BillingResult f2065c;
    public static final BillingResult d;
    public static final BillingResult e;
    public static final BillingResult f;
    public static final BillingResult g;
    public static final BillingResult h;
    public static final BillingResult i;
    public static final BillingResult j;
    public static final BillingResult k;
    public static final BillingResult l;
    public static final BillingResult m;
    public static final BillingResult n;
    public static final BillingResult o;
    public static final BillingResult p;
    public static final BillingResult q;
    public static final BillingResult r;

    static {
        BillingResult.Builder a2 = BillingResult.a();
        a2.f2003a = 3;
        a2.f2004c = "Google Play In-app Billing API version is less than 3";
        a2.a();
        BillingResult.Builder a3 = BillingResult.a();
        a3.f2003a = 3;
        a3.f2004c = "Google Play In-app Billing API version is less than 9";
        f2064a = a3.a();
        BillingResult.Builder a4 = BillingResult.a();
        a4.f2003a = 3;
        a4.f2004c = "Billing service unavailable on device.";
        b = a4.a();
        BillingResult.Builder a5 = BillingResult.a();
        a5.f2003a = 2;
        a5.f2004c = "Billing service unavailable on device.";
        f2065c = a5.a();
        BillingResult.Builder a6 = BillingResult.a();
        a6.f2003a = 5;
        a6.f2004c = "Client is already in the process of connecting to billing service.";
        d = a6.a();
        BillingResult.Builder a7 = BillingResult.a();
        a7.f2003a = 5;
        a7.f2004c = "The list of SKUs can't be empty.";
        a7.a();
        BillingResult.Builder a8 = BillingResult.a();
        a8.f2003a = 5;
        a8.f2004c = "SKU type can't be empty.";
        a8.a();
        BillingResult.Builder a9 = BillingResult.a();
        a9.f2003a = 5;
        a9.f2004c = "Product type can't be empty.";
        e = a9.a();
        BillingResult.Builder a10 = BillingResult.a();
        a10.f2003a = -2;
        a10.f2004c = "Client does not support extra params.";
        f = a10.a();
        BillingResult.Builder a11 = BillingResult.a();
        a11.f2003a = 5;
        a11.f2004c = "Invalid purchase token.";
        g = a11.a();
        BillingResult.Builder a12 = BillingResult.a();
        a12.f2003a = 6;
        a12.f2004c = "An internal error occurred.";
        h = a12.a();
        BillingResult.Builder a13 = BillingResult.a();
        a13.f2003a = 5;
        a13.f2004c = "SKU can't be null.";
        a13.a();
        BillingResult.Builder a14 = BillingResult.a();
        a14.f2003a = 0;
        i = a14.a();
        BillingResult.Builder a15 = BillingResult.a();
        a15.f2003a = -1;
        a15.f2004c = "Service connection is disconnected.";
        j = a15.a();
        BillingResult.Builder a16 = BillingResult.a();
        a16.f2003a = 2;
        a16.f2004c = "Timeout communicating with service.";
        k = a16.a();
        BillingResult.Builder a17 = BillingResult.a();
        a17.f2003a = -2;
        a17.f2004c = "Client does not support subscriptions.";
        l = a17.a();
        BillingResult.Builder a18 = BillingResult.a();
        a18.f2003a = -2;
        a18.f2004c = "Client does not support subscriptions update.";
        a18.a();
        BillingResult.Builder a19 = BillingResult.a();
        a19.f2003a = -2;
        a19.f2004c = "Client does not support get purchase history.";
        a19.a();
        BillingResult.Builder a20 = BillingResult.a();
        a20.f2003a = -2;
        a20.f2004c = "Client does not support price change confirmation.";
        a20.a();
        BillingResult.Builder a21 = BillingResult.a();
        a21.f2003a = -2;
        a21.f2004c = "Play Store version installed does not support cross selling products.";
        a21.a();
        BillingResult.Builder a22 = BillingResult.a();
        a22.f2003a = -2;
        a22.f2004c = "Client does not support multi-item purchases.";
        m = a22.a();
        BillingResult.Builder a23 = BillingResult.a();
        a23.f2003a = -2;
        a23.f2004c = "Client does not support offer_id_token.";
        n = a23.a();
        BillingResult.Builder a24 = BillingResult.a();
        a24.f2003a = -2;
        a24.f2004c = "Client does not support ProductDetails.";
        o = a24.a();
        BillingResult.Builder a25 = BillingResult.a();
        a25.f2003a = -2;
        a25.f2004c = "Client does not support in-app messages.";
        a25.a();
        BillingResult.Builder a26 = BillingResult.a();
        a26.f2003a = -2;
        a26.f2004c = "Client does not support user choice billing.";
        a26.a();
        BillingResult.Builder a27 = BillingResult.a();
        a27.f2003a = -2;
        a27.f2004c = "Play Store version installed does not support external offer.";
        a27.a();
        BillingResult.Builder a28 = BillingResult.a();
        a28.f2003a = -2;
        a28.f2004c = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        a28.a();
        BillingResult.Builder a29 = BillingResult.a();
        a29.f2003a = -2;
        a29.f2004c = "Play Store version installed does not support querying AutoPay plan purchase.";
        a29.a();
        BillingResult.Builder a30 = BillingResult.a();
        a30.f2003a = -2;
        a30.f2004c = "Play Store version installed does not support including suspended subscriptions.";
        a30.a();
        BillingResult.Builder a31 = BillingResult.a();
        a31.f2003a = 5;
        a31.f2004c = "Unknown feature";
        a31.a();
        BillingResult.Builder a32 = BillingResult.a();
        a32.f2003a = -2;
        a32.f2004c = "Play Store version installed does not support get billing config.";
        a32.a();
        BillingResult.Builder a33 = BillingResult.a();
        a33.f2003a = -2;
        a33.f2004c = "Query product details with serialized docid is not supported.";
        a33.a();
        BillingResult.Builder a34 = BillingResult.a();
        a34.f2003a = -2;
        a34.f2004c = "Play Store version installed does not support launching external offer flow.";
        a34.a();
        BillingResult.Builder a35 = BillingResult.a();
        a35.f2003a = 4;
        a35.f2004c = "Item is unavailable for purchase.";
        p = a35.a();
        BillingResult.Builder a36 = BillingResult.a();
        a36.f2003a = -2;
        a36.f2004c = "Query product details with developer specified account is not supported.";
        a36.a();
        BillingResult.Builder a37 = BillingResult.a();
        a37.f2003a = -2;
        a37.f2004c = "Play Store version installed does not support alternative billing only.";
        a37.a();
        BillingResult.Builder a38 = BillingResult.a();
        a38.f2003a = 5;
        a38.f2004c = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        q = a38.a();
        BillingResult.Builder a39 = BillingResult.a();
        a39.f2003a = 6;
        a39.f2004c = "An error occurred while retrieving billing override.";
        r = a39.a();
        BillingResult.Builder a40 = BillingResult.a();
        a40.f2003a = -2;
        a40.f2004c = "Play Store version installed does not support the provided billing program.";
        a40.a();
        BillingResult.Builder a41 = BillingResult.a();
        a41.f2003a = -2;
        a41.f2004c = "Play Store version installed does not support launching external links.";
        a41.a();
    }

    public static BillingResult a(int i2, String str) {
        BillingResult.Builder a2 = BillingResult.a();
        a2.f2003a = i2;
        a2.f2004c = str;
        return a2.a();
    }
}
